-- Written by Clayton Durepos

-- Auto-generated schema initialization file
-- Generated by db/generate_schema.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/schema/*.sql files

-- Source: faculty.sql

CREATE TABLE IF NOT EXISTS faculty (
    faculty_id          CHAR(36)        PRIMARY KEY,
    
    -- Keep first name `NOT NULL` to ensure some info is stored for any instance
    first_name          VARCHAR(128)    NOT NULL,
    last_name           VARCHAR(128),
    biography           VARCHAR(2048),
    orcid               CHAR(19),
    google_scholar_url  VARCHAR(255),
    research_gate_url   VARCHAR(255),

    -- Store URLs we retrieved a users info from
    -- Better transparency with users
    scraped_from        VARCHAR(255),
    
    CHECK (
        (google_scholar_url IS NULL 
            OR google_scholar_url LIKE 'https://scholar.google.com/%'
            OR google_scholar_url LIKE 'http://scholar.google.com/%')
        AND
        (research_gate_url IS NULL
            OR research_gate_url LIKE 'https://www.researchgate.net/%'
            OR research_gate_url LIKE 'http://www.researchgate.net/%')
    ),

    -- Index on last name and first name for faster search functionality
    INDEX idx_faculty_last_name (last_name),
    INDEX idx_faculty_first_name (first_name)
);

-- Source: institution.sql

-- Institution schema
CREATE TABLE IF NOT EXISTS institution (
    institution_id      CHAR(36)        PRIMARY KEY,
    name                VARCHAR(256)    NOT NULL,

    -- Location composite attributes
    street_addr         VARCHAR(255),
    city                VARCHAR(255),
    state               VARCHAR(255),
    country             VARCHAR(255) NOT NULL,
    zip                 VARCHAR(16),

    website_url         VARCHAR(255),
    type                ENUM(
                            "Public University", 
                            "Private University", 
                            "Community College"
                        ),


    -- Constraints
    CHECK (zip IS NULL OR zip REGEXP '^[0-9]{5}$'),

    -- Index on institution name for faster lookup
    INDEX idx_institution_name (name),

    -- Index on city and state for regional searches
    INDEX idx_institution_city_state (city, state),

    -- Index on zip code for a more specific location lookup
    INDEX idx_institution_zip (zip)
);


-- Source: keyword.sql

CREATE TABLE keyword (
    name VARCHAR(64) PRIMARY KEY
);

-- Source: publication.sql

CREATE TABLE IF NOT EXISTS publication (
    publication_id  CHAR(36) NOT NULL PRIMARY KEY,

    title           VARCHAR(128) NOT NULL,
    year            INT NOT NULL,
    doi             VARCHAR(64) UNIQUE,
    abstract        TEXT,
    publisher       VARCHAR(64) NOT NULL,
    citation_count  INT DEFAULT 0
);

-- Source: grants.sql

CREATE TABLE IF NOT EXISTS grants (
    grant_id    CHAR(36)        PRIMARY KEY,
    description VARCHAR(2048)   NULL,
    amount      DECIMAL(10,2)   NOT NULL,
    start_date  DATE            NOT NULL,
    end_date    DATE            NULL
);


-- Source: session.sql

-- SESSION SCHEMA
-- Stores hashed refresh tokens for long-term authentication sessions
CREATE TABLE IF NOT EXISTS session (
    -- Primary key
    session_id              CHAR(36)        PRIMARY KEY,
    
    -- Associated faculty member
    faculty_id           CHAR(36)         NOT NULL,
    
    -- Hash of the refresh token (SHA-256)
    -- Never store the raw token, only the hash
    token_hash           VARCHAR(64)      NOT NULL UNIQUE,
    
    -- When this session was created
    created_at           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- When this token expires (typically 7-30 days)
    expires_at           DATETIME         NOT NULL,

    -- Whether this session has been revoked
    revoked              BOOLEAN          NOT NULL DEFAULT FALSE,
    
    -- Foreign key constraint
    FOREIGN KEY (faculty_id)
        REFERENCES faculty (faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    -- Index for lookups by faculty_id
    INDEX idx_faculty_id (faculty_id),
    
    -- Index for lookups by token_hash
    INDEX idx_token_hash (token_hash),
    
    -- Index for cleanup of expired tokens
    INDEX idx_expires_at (expires_at)
);



-- Source: credentials.sql

-- USER CREDENTIALS SCHEMA
CREATE TABLE IF NOT EXISTS credentials (
    -- ASSOCIATED USER ID
    faculty_id        CHAR(36)      NOT NULL UNIQUE,

    username          VARCHAR(255)  NOT NULL UNIQUE,

    -- HASH OF PW
    password_hash     VARCHAR(255)  NOT NULL,

    -- PW SALT FOR SECURITY
    password_salt     VARCHAR(255)  NOT NULL,

    -- TRACK LAST LOGIN
    last_login        DATETIME      NULL,

    PRIMARY KEY (faculty_id),

    FOREIGN KEY (faculty_id)
        REFERENCES faculty (faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- Source: equipment.sql

-- EQUIPMENT SCH
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id            CHAR(36)        PRIMARY KEY,
    name                    VARCHAR(64)     NOT NULL,

    -- Description of the equipment itself
    description             VARCHAR(2048),

    -- TEXT DEFAULT
    -- Allow for simple phrases `Available,` `Unavailable,` etc.
    -- In addition to descriptive passages...
    -- `Available Mondays 14:00-20:00 ...`
    availability            VARCHAR(2048)            NOT NULL,

    -- Each Equipment must belong to exactly one Institution
    institution_id          CHAR(36)    NOT NULL,
    FOREIGN KEY (institution_id)
        REFERENCES institution(institution_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on institution_id for faster lookup related to institution
    INDEX idx_equipment_institution_id (institution_id),

    -- Index on equipment name
    INDEX idx_equipment_name (name),

    -- Quickly check availability (using prefix index due to VARCHAR(2048) length)
    INDEX idx_equipment_availability (availability(255))
);


-- Source: faculty_department.sql

CREATE TABLE IF NOT EXISTS faculty_department (
    faculty_id      CHAR(36)        NOT NULL,
    department_name VARCHAR(128),

    PRIMARY KEY (faculty_id, department_name),

    FOREIGN KEY (faculty_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on department name for faster search functionality
    INDEX idx_faculty_department_dept_name (department_name)
);

-- Source: faculty_email.sql

CREATE TABLE IF NOT EXISTS faculty_email (
    faculty_id  CHAR(36)        NOT NULL,
    email       VARCHAR(255),

    PRIMARY KEY (faculty_id, email),

    FOREIGN KEY (faculty_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- RegEx to check that email is indeed an email
    CHECK (email IS NULL OR email LIKE '%_@__%.__%')
);

-- Source: faculty_generates_keyword.sql

CREATE TABLE IF NOT EXISTS faculty_generates_keyword (
    generation_id    CHAR(36)        PRIMARY KEY,
    faculty_id       CHAR(36)        NOT NULL,
    generated_at     DATETIME        NOT NULL,

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);



-- Source: faculty_phone.sql

CREATE TABLE IF NOT EXISTS faculty_phone (
    faculty_id  CHAR(36)        NOT NULL,

    -- (Estimated) Max phone number length is 15 digits
    -- 32 Char max for extra space
    phone_num   VARCHAR(32),

    PRIMARY KEY (faculty_id, phone_num),

    FOREIGN KEY (faculty_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
);

-- Source: faculty_title.sql

CREATE TABLE IF NOT EXISTS faculty_title (
    faculty_id  CHAR(36)        NOT NULL,
    title       VARCHAR(255),

    PRIMARY KEY (faculty_id, title),
    FOREIGN KEY (faculty_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Source: grants_organization.sql

-- GRANT ORG SCHEMA
-- Not all organizations that fund a grant may be an educational or research institution
-- We store the names of funding org's as a MV attribute of grants 
-- Rather than creating an instance of institution for every funding agency
CREATE TABLE grants_organization (
    grant_id       CHAR(36)     NOT NULL,
    name           VARCHAR(255) NOT NULL,

    PRIMARY KEY (grant_id, name),

    FOREIGN KEY (grant_id)
        REFERENCES grants (grant_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on grant_id to optimize lookup for organizations associated with a given grant
    INDEX idx_grant_id (grant_id)
);


-- Source: faculty_follows_faculty.sql

CREATE TABLE IF NOT EXISTS faculty_follows_faculty(
    follower_id     CHAR(36)    NOT NULL,
    followee_id     CHAR(36)    NOT NULL,

    PRIMARY KEY (follower_id, followee_id),
    FOREIGN KEY (follower_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    FOREIGN KEY (followee_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Source: faculty_recommended_to_faculty.sql

/**
 * Faculty-to-faculty recommendations.
 * ENUM order defines priority (first = highest).
 */
CREATE TABLE IF NOT EXISTS faculty_recommended_to_faculty (
    source_faculty_id   CHAR(36) NOT NULL,
    target_faculty_id   CHAR(36) NOT NULL,
    recommendation_type ENUM(
        'shared_keyword',
        'keyword_to_publication',
        'publication_to_keyword',
        'keyword_to_grant',
        'grant_to_keyword',
        'grant_to_publication',
        'publication_to_grant',
        'shared_grant',
        'shared_department'
    ) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (source_faculty_id, target_faculty_id),

    FOREIGN KEY (source_faculty_id) 
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE ON UPDATE CASCADE,

    FOREIGN KEY (target_faculty_id)
        REFERENCES faculty(faculty_id) 
        ON DELETE CASCADE ON UPDATE CASCADE,

    INDEX idx_recommendations_source (source_faculty_id),
    INDEX idx_recommendations_type (recommendation_type)
);


-- Source: faculty_researches_keyword.sql

CREATE TABLE faculty_researches_keyword (
    name        VARCHAR(64)     NOT NULL,
    faculty_id     CHAR(36)     NOT NULL,

    PRIMARY KEY (name, faculty_id),

    FOREIGN KEY (name)
        REFERENCES keyword(name)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on faculty_id for lookups by faculty (batch keyword retrieval)
    INDEX idx_frk_faculty_id (faculty_id)
);


-- Source: faculty_works_at_institution.sql

-- Represents the many-to-many relation between Faculty and Institution
CREATE TABLE faculty_works_at_institution (
    faculty_id      CHAR(36)    NOT NULL,
    institution_id  CHAR(36)    NOT NULL,

    start_date      DATE        NOT NULL,

    -- Nullable end date
    -- Users may currently work at an institution
    end_date        DATE,

    PRIMARY KEY (faculty_id, institution_id),

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (institution_id)
        REFERENCES institution(institution_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on institution_id for joins from institution side
    INDEX idx_fwai_institution_id (institution_id)
);

-- Source: grants_for_keyword.sql

CREATE TABLE grants_for_keyword (
    grant_id        CHAR(36)    NOT NULL,
    name            VARCHAR(64) NOT NULL,

    PRIMARY KEY (name, grant_id),

    FOREIGN KEY (name)
        REFERENCES keyword(name)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY(grant_id)
        REFERENCES grants(grant_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Source: grants_granted_to_faculty.sql

CREATE TABLE grants_granted_to_faculty (
    grant_id        CHAR(36)    NOT NULL,
    faculty_id      CHAR(36)    NOT NULL,

    PRIMARY KEY (grant_id, faculty_id),

    FOREIGN KEY (grant_id)
        REFERENCES grants(grant_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- Source: publication_authored_by_faculty.sql

CREATE TABLE IF NOT EXISTS publication_authored_by_faculty (
    faculty_id         CHAR(36)    NOT NULL,
    publication_id  CHAR(36)    NOT NULL,

    PRIMARY KEY (faculty_id, publication_id),

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    FOREIGN KEY (publication_id)
        REFERENCES publication(publication_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Index on publication_id for joins from publication side (keyword searches)
    INDEX idx_pabf_publication_id (publication_id)
);


-- Source: publication_explores_keyword.sql

CREATE TABLE publication_explores_keyword (
    publication_id  CHAR(36)    NOT NULL,
    name            VARCHAR(64) NOT NULL,

    PRIMARY KEY (publication_id, name),

    FOREIGN KEY (publication_id)
        REFERENCES publication(publication_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    FOREIGN KEY (name)
        REFERENCES keyword(name)
        ON DELETE CASCADE
        ON UPDATE CASCADE

);


