-- Auto-generated functions file
-- Generated by db/generate_functions.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/functions/*.sql files

-- Source: count_keyword.sql

DELIMITER $$

DROP FUNCTION IF EXISTS count_keywords$$
CREATE FUNCTION count_keywords()
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM keyword;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: count_keywords_publication.sql

DELIMITER $$

DROP FUNCTION IF EXISTS count_keywords_publication$$
CREATE FUNCTION count_keywords_publication(
    p_publication_id CHAR(36)
)
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM publication_keywords
    WHERE publication_id = p_publication_id;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: count_user_keywords.sql

DELIMITER $$

DROP FUNCTION IF EXISTS count_user_keywords$$
CREATE FUNCTION count_user_keywords(
    p_faculty_id CHAR(36)
)
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM user_keywords
    WHERE faculty_id = p_faculty_id;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: get_citation_count.sql

DELIMITER $$

DROP FUNCTION IF EXISTS get_citation_count$$
CREATE FUNCTION get_citation_count(p_publication_id CHAR(36))
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_count INT;

    SELECT citation_count INTO v_count
    FROM publications
    WHERE publication_id = p_publication_id;

    RETURN v_count;
END $$

DELIMITER ;


-- Source: get_DOI.sql

DELIMITER $$

DROP FUNCTION IF EXISTS get_DOI$$
CREATE FUNCTION get_DOI(p_id CHAR(36))
RETURNS VARCHAR(64)
READS SQL DATA
BEGIN
    DECLARE v_pub_doi VARCHAR(64);
    SELECT doi INTO v_pub_doi
    FROM publications
    WHERE publication_id = p_id;
    RETURN v_pub_doi;
END $$
DELIMITER ;


-- Source: get_publication_title.sql

DELIMITER $$

DROP FUNCTION IF EXISTS get_publication_title$$
CREATE FUNCTION get_publication_title(p_publication_id CHAR(36))
RETURNS VARCHAR(128)
READS SQL DATA
BEGIN
    DECLARE v_title VARCHAR(128);

    SELECT title INTO v_title
    FROM publications
    WHERE publication_id = p_publication_id;

    RETURN v_title;
END $$

DELIMITER ;


-- Source: get_publication_year.sql

DELIMITER $$

DROP FUNCTION IF EXISTS get_publication_year$$
CREATE FUNCTION get_publication_year(p_publication_id CHAR(36))
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_year INT;

    SELECT year INTO v_year
    FROM publications
    WHERE publication_id = p_publication_id;
    RETURN v_year;
END $$

DELIMITER ;


-- Source: grants_status.sql

DELIMITER $$

DROP FUNCTION IF EXISTS grant_status$$

CREATE FUNCTION grant_status(
    p_start_date  DATE,
    p_end_date    DATE
) RETURNS VARCHAR(16)
READS SQL DATA
BEGIN
    IF p_start_date > CURDATE() THEN
        RETURN 'UPCOMING';
    END IF;

    IF p_start_date <= CURDATE() AND p_end_date >= CURDATE() THEN
        RETURN 'ACTIVE';
    END IF;

    IF p_end_date < CURDATE() THEN
        RETURN 'EXPIRED';
    END IF;
    
    -- Default case (should not happen, but handle NULL dates)
    RETURN NULL;
END $$
DELIMITER ;


-- Source: hash_password.sql

DELIMITER $$

DROP FUNCTION IF EXISTS hash_password$$
CREATE FUNCTION hash_password(
    p_plain_text     VARCHAR(255),
    p_salt          VARCHAR(255)
) RETURNS CHAR(64)
DETERMINISTIC
BEGIN
    -- Hex-encoded SHA-256 = 64 characters
    RETURN SHA2(CONCAT(p_plain_text, p_salt), 256);
END $$

DELIMITER ;


-- Source: is_grants_active.sql

DELIMITER $$

DROP FUNCTION IF EXISTS is_grant_active$$

CREATE FUNCTION is_grant_active(
    p_start_date DATE,
    p_end_date   DATE
) RETURNS BOOLEAN
READS SQL DATA
BEGIN
    RETURN grant_status(p_start_date, p_end_date) = 'ACTIVE';
END $$
DELIMITER ;


-- Source: keyword_exists.sql

DELIMITER $$

DROP FUNCTION IF EXISTS keyword_exists$$
CREATE FUNCTION keyword_exists(p_name VARCHAR(64))
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM keyword
        WHERE name = p_name
    );
END $$

DELIMITER ;


-- Source: publication_has_keyword.sql

DELIMITER $$

DROP FUNCTION IF EXISTS publication_has_keyword$$
CREATE FUNCTION publication_has_keyword(
    p_publication_id CHAR(36),
    p_name VARCHAR(64)
)
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM publication_keywords
        WHERE publication_id = p_publication_id
          AND name = p_name
    );
END $$

DELIMITER ;


-- Source: user_has_keyword.sql

DELIMITER $$

DROP FUNCTION IF EXISTS user_has_keyword$$
CREATE FUNCTION user_has_keyword(
    p_faculty_id CHAR(36),
    p_name VARCHAR(64)
)
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM user_keywords
        WHERE faculty_id = p_faculty_id
          AND name = p_name
    );
END $$

DELIMITER ;


