-- Auto-generated functions file
-- Generated by db/generate_functions.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/functions/*.sql files

-- Source: count_keyword.sql

DELIMITER $$

CREATE FUNCTION count_keywords()
RETURNS INT
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM keyword;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: count_keywords_publication.sql

DELIMITER $$

CREATE FUNCTION count_keywords_publication(
    IN p_publication_id CHAR(36)
)
RETURNS INT
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM publication_keywords
    WHERE publication_id = p_publication_id;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: count_user_keywords.sql

DELIMITER $$

CREATE FUNCTION count_user_keywords(
    IN p_faculty_id CHAR(36)
)
RETURNS INT
BEGIN
    DECLARE v_total INT;

    SELECT COUNT(*) INTO v_total
    FROM user_keywords
    WHERE faculty_id = p_faculty_id;

    RETURN v_total;
END $$

DELIMITER ;


-- Source: get_DOI.sql

DELIMITER $$

CREATE FUNCTION get_DOI(p_id CHAR(36))
RETURNS VARCHAR(64)
BEGIN
    DECLARE v_pub_doi VARCHAR(64);
    SELECT doi INTO v_pub_doi
    FROM publications
    WHERE publication_id = p_id;
    RETURN v_pub_doi;
END $$
DELIMITER ;


-- Source: get_citation_count.sql

DELIMITER $$

CREATE FUNCTION get_citation_count(p_publication_id CHAR(36))
RETURNS INT
BEGIN
    DECLARE v_count INT;

    SELECT citation_count INTO v_count
    FROM publications
    WHERE publication_id = p_publication_id;

    RETURN v_count;
END $$

DELIMITER ;


-- Source: get_publication_title.sql

DELIMITER $$

CREATE FUNCTION get_publication_title(p_publication_id CHAR(36))
RETURNS VARCHAR(64)
BEGIN
    DECLARE v_title VARCHAR(64);

    SELECT title INTO v_title
    FROM publications
    WHERE publication_id = p_publication_id;

    RETURN v_title;
END $$

DELIMITER ;


-- Source: get_publication_year.sql

DELIMITER $$

CREATE FUNCTION get_publication_year(p_publication_id CHAR(36))
RETURNS INT
BEGIN
    DECLARE v_year INT;

    SELECT year INTO v_year
    FROM publications
    WHERE publication_id = p_publication_id;
    RETURN v_year;
END $$

DELIMITER ;


-- Source: grants_status.sql

DELIMITER $$

DROP FUNCTION IF EXISTS grant_status;

CREATE FUNCTION grant_status(
    p_start_date  DATE,
    p_end_date    DATE
) RETURNS VARCHAR(16)
BEGIN
    IF p_start_date > CURDATE() THEN
        RETURN `UPCOMING`;
    END IF;

    IF p_start_date <= CURDATE() and p_end_date >= CURDATE() THEN
        RETURN `ACTIVE`;
    END IF;

    IF p_end_date < CURDATE() THEN
        RETURN `EXPIRED`;
    END IF;
END $$
DELIMITER ;


-- Source: hash_password.sql

DELIMITER $$

DROP FUNCTION IF EXISTS hash_password;
CREATE FUNCTION fn_hash_password(
    p_plain_text     VARCHAR(255),
    p_salt          VARCHAR(255)
) RETURNS CHAR(64)
BEGIN
    -- Hex-encoded SHA-256 = 64 characters
    RETURN SHA2(CONCAT(p_plain_text, p_salt), 256);
END $$

DELIMITER ;


-- Source: is_grants_active.sql

DELIMITER $$

DROP FUNCTION IF EXISTS is_grant_active;

CREATE FUNCTION is_grant_active(
    p_start_date DATE,
    p_end_date   DATE
) RETURNS BOOLEAN
BEGIN
    RETURN grant_status(p_start_date, p_end_date) = `ACTIVE`;
END $$
DELIMITER ;


-- Source: keyword_exists.sql

DELIMITER $$

CREATE FUNCTION keyword_exists(p_name VARCHAR(64))
RETURNS BOOLEAN
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM keyword
        WHERE name = p_name
    );
END $$

DELIMITER ;


-- Source: publication_has_keyword.sql

DELIMITER $$

CREATE FUNCTION publication_has_keyword(
    IN p_publication_id CHAR(36),
    IN p_name VARCHAR(64)
)
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM publication_keywords
        WHERE publication_id = p_publication_id
          AND name = p_name
    );
END $$

DELIMITER ;


-- Source: user_has_keyword.sql

DELIMITER $$

CREATE FUNCTION user_has_keyword(
    IN p_faculty_id CHAR(36),
    IN p_name VARCHAR(64)
)
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM user_keywords
        WHERE faculty_id = p_faculty_id
          AND name = p_name
    );
END $$

DELIMITER ;


