-- Auto-generated events file
-- Generated by db/generate_events.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/events/*.sql files

-- Enable the MySQL event scheduler
-- This must be enabled for scheduled events to run
-- [WARNING] Restarting the mysql server will reset the event scheduler to OFF. Set it to ON in my.cnf so it starts automatically on server startup/restart.
SET GLOBAL event_scheduler = ON;

-- Source: clean_faculty_generates_keyword_event.sql

DELIMITER $$

/**
 * Scheduled event to automatically clean up old keyword generation records.
 * 
 * This event runs periodically to remove generation records that are older
 * than a specified threshold (default: 1 hour). This helps maintain the database
 * by automatically removing records that are no longer relevant for rate limiting.
 * 
 * The event is scheduled to run every hour.
 * 
 * Note: Events require the MySQL event scheduler to be enabled.
 * Enable with: SET GLOBAL event_scheduler = ON;
 * 
 * To modify the cleanup threshold, edit the DATE_SUB interval below.
 * Current setting: 1 HOUR (deletes records older than 1 hour)
 */
DROP EVENT IF EXISTS clean_faculty_generates_keyword_event$$

CREATE EVENT clean_faculty_generates_keyword_event
ON SCHEDULE EVERY 1 HOUR
STARTS CURRENT_TIMESTAMP
ON COMPLETION PRESERVE
ENABLE
COMMENT 'Automatically cleans up old keyword generation records hourly'
DO
BEGIN
    -- Call the cleanup procedure to delete records older than 1 hour
    CALL clean_faculty_generates_keyword(DATE_SUB(NOW(), INTERVAL 1 HOUR));
END $$

DELIMITER ;



-- Source: clean_session_event.sql

DELIMITER $$

/**
 * Scheduled event to automatically clean up expired and old revoked sessions.
 * 
 * This event runs periodically to remove:
 *   - All sessions that have passed their expiration date
 *   - All revoked sessions older than 30 days (for audit trail retention)
 * 
 * This helps maintain the database by automatically removing sessions that are
 * no longer valid or needed for auditing purposes.
 * 
 * The event is scheduled to run daily at 2:00 AM UTC.
 * 
 * Note: Events require the MySQL event scheduler to be enabled.
 * Enable with: SET GLOBAL event_scheduler = ON;
 */
DROP EVENT IF EXISTS clean_session_event$$

CREATE EVENT clean_session_event
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_DATE + INTERVAL 1 DAY + INTERVAL 2 HOUR
ON COMPLETION PRESERVE
ENABLE
COMMENT 'Automatically cleans up expired and old revoked sessions daily'
DO
BEGIN
    -- Call the cleanup procedure to delete expired sessions and old revoked sessions
    CALL clean_session();
END $$

DELIMITER ;



-- Source: generate_recommendations_event.sql

DELIMITER $$

/**
 * Scheduled event to generate faculty recommendations every 12 hours.
 * 
 * Runs the generate_all_recommendations procedure twice daily to keep
 * recommendations fresh as new faculty register and update their profiles.
 * 
 * Schedule: Every 12 hours, starting at 2 AM UTC
 */
DROP EVENT IF EXISTS generate_recommendations_event$$

CREATE EVENT generate_recommendations_event
ON SCHEDULE 
    EVERY 12 HOUR
    STARTS CURRENT_DATE + INTERVAL 2 HOUR
COMMENT 'Generate faculty recommendations every 12 hours'
DO
BEGIN
    CALL generate_all_recommendations();
END $$

DELIMITER ;



