#!/bin/bash

# Script to generate 003_add_functions.sql from all files in the functions directory
# Ignores *.md files

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
FUNCTIONS_DIR="$SCRIPT_DIR/functions"
OUTPUT_FILE="$SCRIPT_DIR/init/003_init_functions.sql"

# Create migrations directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Clear the output file
> "$OUTPUT_FILE"

# Add header comment
cat >> "$OUTPUT_FILE" << 'EOF'
-- Auto-generated functions file
-- Generated by db/generate_functions.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/functions/*.sql files

EOF

# Find all .sql files in functions directory (excluding .md files), sort them, and concatenate
find "$FUNCTIONS_DIR" -maxdepth 1 -name "*.sql" -type f | sort | while read -r file; do
    echo "-- Source: $(basename "$file")" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo "[OK] Generated $OUTPUT_FILE"

