#!/bin/bash

# Script to generate 001_init_schema.sql from all files in the schema directory
# Ignores *.md files

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCHEMA_DIR="$SCRIPT_DIR/schema"
OUTPUT_FILE="$SCRIPT_DIR/init/001_init_schema.sql"

# Create migrations directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Clear the output file
> "$OUTPUT_FILE"

# Add header comment
cat >> "$OUTPUT_FILE" << 'EOF'
-- Auto-generated schema initialization file
-- Generated by db/generate_schema.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/schema/*.sql files

EOF

# Define the order of table creation to respect foreign key dependencies
# Base tables first (no foreign keys to other tables in this schema)
BASE_TABLES=(
    "faculty.sql"
    "institution.sql"
    "keyword.sql"
    "publication.sql"
    "grants.sql"
)

# Tables that reference only one base table
SINGLE_REF_TABLES=(
    "credentials.sql"              # references faculty
    "equipment.sql"               # references institution
    "faculty_department.sql"      # references faculty
    "faculty_email.sql"           # references faculty
    "faculty_generates_keyword.sql" # references faculty
    "faculty_phone.sql"           # references faculty
    "faculty_title.sql"           # references faculty
     "grants_organization.sql"    # references grants
)

# Tables that reference multiple base tables or other relationship tables
MULTI_REF_TABLES=(
    "faculty_follows_faculty.sql"           # references faculty (twice)
    "faculty_recommended_to_faculty.sql"     # references faculty (twice)
    "faculty_researches_keyword.sql"         # references faculty and keyword
    "faculty_works_at_institution.sql"       # references faculty and institution
    "grants_for_keyword.sql"                 # references grants and keyword
    "grants_granted_to_faculty.sql"          # references grants and faculty
    "publication_authored_by_faculty.sql"    # references publication and faculty
    "publication_explores_keyword.sql"       # references publication and keyword
)

# Function to add a file to the output if it exists
add_file() {
    local file="$SCHEMA_DIR/$1"
    if [ -f "$file" ]; then
        echo "-- Source: $1" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
}

# Add base tables first
for table in "${BASE_TABLES[@]}"; do
    add_file "$table"
done

# Add single-reference tables
for table in "${SINGLE_REF_TABLES[@]}"; do
    add_file "$table"
done

# Add multi-reference tables
for table in "${MULTI_REF_TABLES[@]}"; do
    add_file "$table"
done

echo "[OK] Generated $OUTPUT_FILE"

