#!/bin/bash

# Script to generate 002_add_procedures.sql from all files in the procedures subdirectories
# Ignores *.md files
# Processes subdirectories in order: create, read, update, delete, workflow

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROCEDURES_DIR="$SCRIPT_DIR/procedures"
OUTPUT_FILE="$SCRIPT_DIR/init/002_init_procedures.sql"

# Create migrations directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Clear the output file
> "$OUTPUT_FILE"

# Add header comment
cat >> "$OUTPUT_FILE" << 'EOF'
-- Auto-generated procedures file
-- Generated by db/generate_procedures.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/procedures/**/*.sql files

EOF

# Define the order of subdirectories to process
SUBDIRS=("create" "read" "update" "delete" "workflow")

# Process each subdirectory in order
for subdir in "${SUBDIRS[@]}"; do
    subdir_path="$PROCEDURES_DIR/$subdir"
    
    if [ ! -d "$subdir_path" ]; then
        echo "[WARN] Subdirectory not found: $subdir_path"
        continue
    fi
    
    # Add section header
    echo "-- ============================================================" >> "$OUTPUT_FILE"
    echo "-- $subdir procedures" >> "$OUTPUT_FILE"
    echo "-- ============================================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Find all .sql files in this subdirectory (excluding .md files), sort them, and concatenate
    find "$subdir_path" -maxdepth 1 -name "*.sql" -type f | sort | while read -r file; do
        echo "-- Source: $subdir/$(basename "$file")" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
done

echo "[OK] Generated $OUTPUT_FILE"

