#!/bin/bash

# Written by Aidan Bell

# Script to generate 004_init_events.sql from all files in the events directory
# Ignores *.md files

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
EVENTS_DIR="$SCRIPT_DIR/events"
OUTPUT_FILE="$SCRIPT_DIR/init/004_init_events.sql"

# Create init directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Clear the output file
> "$OUTPUT_FILE"

# Add header comment
cat >> "$OUTPUT_FILE" << 'EOF'
-- Auto-generated events file
-- Generated by db/generate_events.sh
-- DO NOT EDIT MANUALLY - This file is generated from db/events/*.sql files

-- Enable the MySQL event scheduler
-- This must be enabled for scheduled events to run
-- [WARNING] Restarting the mysql server will reset the event scheduler to OFF. Set it to ON in my.cnf so it starts automatically on server startup/restart.
SET GLOBAL event_scheduler = ON;

EOF

# Find all .sql files in events directory (excluding .md files), sort them, and concatenate
find "$EVENTS_DIR" -maxdepth 1 -name "*.sql" -type f | sort | while read -r file; do
    echo "-- Source: $(basename "$file")" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$file" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo "[OK] Generated $OUTPUT_FILE"

