#!/bin/bash

# Written by Clayton Durepos

# Script to generate 002_init_procedures.sql from all files in the procedures subdirectories
# Processes subdirectories in order: util, create, read, update, delete, workflow
# util must come first as it contains functions used by other procedures

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROCEDURES_DIR="$SCRIPT_DIR/procedures"
OUTPUT_FILE="$SCRIPT_DIR/init/002_init_procedures.sql"

mkdir -p "$(dirname "$OUTPUT_FILE")"
> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
-- Auto-generated procedures file
-- Generated by db/generate_procedures.sh
-- DO NOT EDIT MANUALLY

EOF

# util must come first (contains functions used by procedures)
SUBDIRS=("util" "create" "read" "update" "delete" "workflow")

for subdir in "${SUBDIRS[@]}"; do
    subdir_path="$PROCEDURES_DIR/$subdir"
    
    if [ ! -d "$subdir_path" ]; then
        continue
    fi
    
    echo "-- ============================================================" >> "$OUTPUT_FILE"
    echo "-- $subdir" >> "$OUTPUT_FILE"
    echo "-- ============================================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    find "$subdir_path" -name "*.sql" -type f | sort | while read -r file; do
        relative_path="${file#$PROCEDURES_DIR/}"
        echo "-- Source: $relative_path" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
done

echo "[OK] Generated $OUTPUT_FILE"
